version: '2'
services:
  app:
    image: node
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: ['npm', 'start']

  functions:
    image: node
    working_dir: /app
    volumes:
      - ./functions:/app
